export enum ErrorCode {
  BAD_REQUEST = "BAD_REQUEST",
  CLIENT_RESPONSE_NOT_RECEIVED = "CLIENT_RESPONSE_NOT_RECEIVED",
  PERMISSION_DENIED = "PERMISSION_DENIED",
  ACCESS_TOKEN_INVALID = "ACCESS_TOKEN_INVALID",
  USER_DEACTIVATED = "USER_DEACTIVATED",
  NOT_FOUND = "NOT_FOUND",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  TIMECODES_ALREADY_EXIST = "TIMECODES_ALREADY_EXIST"
}
