export enum TwitchContentClassification {
  DRUGS_INTOXICATION_TOBACCO = 100,
  GAMBLING = 101,
  PROFANITY_VULGARITY = 102,
  SEXUAL_THEMES = 103,
  VIOLENT_GRAPHIC = 104,
  POLITICS_AND_SENSITIVE_SOCIAL_ISSUES = 105
}